#!/usr/bin/env python3
"""Generate docs/configuration.md from the Settings model.

Hand-written config docs drift the moment someone adds a field. This reads the
real pydantic model, so the reference is generated from the thing that actually
governs behaviour.

    python scripts/gen_config_docs.py           # write the file
    python scripts/gen_config_docs.py --check   # fail if it is out of date (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "backend"))

from sensei.config import Settings  # noqa: E402

OUT = REPO / "docs" / "configuration.md"

# Field-name prefix/suffix -> section. First match wins; order matters.
SECTIONS: list[tuple[str, str, str]] = [
    # Agents come first so `brave_api_key` lands here rather than being swept
    # up by the `_api_` pattern below.
    ("Agents & tools", "The ReAct loop and what it may touch.", "agent_|web_fetch|brave_|code_exec"),
    ("Models & providers", "How Sensei reaches a model.", "model_provider|api_provider|_api_"),
    ("Local models", "Ollama, llama.cpp and vLLM.", "ollama_|local_"),
    ("Compression", "The pipeline that saves the tokens.", "compression|ccr_|output_shaper|gateway_|usd_per|learned_"),
    ("Server", "Where Sensei listens.", "^host$|^port$|cors_|log_file"),
    ("Security", "Auth, encryption, rate limits, DLP.", "auth|rate_limit|encryption|redaction|blocked_|vault_|max_message|rbac_|admin_emails|oidc_"),
    ("Sessions & data", "What is stored and for how long.", "session_|memory_|audit_|purge_"),
    ("Knowledge base (RAG)", "Documents Sensei can answer from.", "rag_|embeddings_|watch_"),
    ("Integrations", "Webhooks and external channels.", "webhook_"),
]


def _section_for(name: str) -> str:
    import re

    for title, _desc, pattern in SECTIONS:
        if re.search(pattern, name):
            return title
    return "Other"


def _render_default(value: object) -> str:
    if value == "":
        return "_(empty)_"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def build() -> str:
    fields = Settings.model_fields
    grouped: dict[str, list[tuple[str, object, str]]] = {}
    for name, field in fields.items():
        env = f"SENSEI_{name.upper()}"
        grouped.setdefault(_section_for(name), []).append((env, field.default, name))

    lines = [
        "# Configuration",
        "",
        "<!-- Generated by scripts/gen_config_docs.py — do not edit by hand. -->",
        "",
        "Every setting is an environment variable, and every one has a working",
        "default. You can set them in the environment or in a `.env` file at the",
        "repository root; the environment wins.",
        "",
        "**You probably don't need any of this.** `sensei up` opens a setup wizard",
        "that writes what it needs. This page is the reference for when you want",
        "something specific.",
        "",
        "Run `sensei doctor` to see what Sensei has actually resolved at runtime.",
        "",
    ]

    order = [t for t, _, _ in SECTIONS] + ["Other"]
    for title in order:
        entries = grouped.get(title)
        if not entries:
            continue
        desc = next((d for t, d, _ in SECTIONS if t == title), "")
        lines += [f"## {title}", "", desc, "", "| Variable | Default |", "|---|---|"]
        for env, default, _name in sorted(entries):
            lines.append(f"| `{env}` | {_render_default(default)} |")
        lines.append("")

    lines += [
        "## Notes on a few that matter",
        "",
        "**`SENSEI_HOST`** defaults to `127.0.0.1`. Sensei holds your API keys and",
        "your conversation history; it should not be reachable from your network",
        "unless you decide it should. If you set `0.0.0.0`, also set",
        "`SENSEI_AUTH_ENABLED=true` with a strong `SENSEI_AUTH_TOKEN` and put a",
        "TLS-terminating reverse proxy in front — see [deploy/README.md](../deploy/README.md).",
        "",
        "**API keys** entered through the web UI or `PUT /api/settings` are stored in",
        "an encrypted vault, not written to `.env` in plaintext. Keys you put in",
        "`.env` yourself stay where you put them.",
        "",
        "**`SENSEI_CODE_EXEC_ENABLED`** runs `run_python` in a subprocess on this host.",
        "It is not a container and not a sandbox. Leave it off unless you control the",
        "machine and trust what you point the agent at.",
        "",
        "**`SENSEI_GATEWAY_PRESERVE_CACHE`** compresses only the newest message so",
        "earlier turns stay byte-exact and the provider's prompt cache still hits.",
        "Slightly less compression, materially lower latency for cache-heavy agents",
        "like Claude Code.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    generated = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print(
                "docs/configuration.md is out of date.\n"
                "Regenerate it with: python scripts/gen_config_docs.py",
                file=sys.stderr,
            )
            return 1
        print("docs/configuration.md is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(Settings.model_fields)} settings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
