#!/usr/bin/env python3
"""Render Homebrew, Scoop and winget manifests from a finished release.

Package managers all want the same two facts — a URL and a sha256 — and all
want them in a different file format. Writing those by hand once per release is
how a formula ends up pinning the checksum of the version before last, which
fails in the least helpful way possible: the download succeeds and the
verification does not.

This reads the `SHA256SUMS` that the release job has already produced, so the
checksums in the manifests are by construction the checksums of the artifacts
that were actually uploaded.

    python scripts/render_manifests.py --version 0.1.0 \\
        --sums release/SHA256SUMS --out release/manifests

The rendered files are attached to the release. Getting them into the actual
package managers is a separate, one-time-per-manager step — see
docs/packaging.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = "SenseiIssei/Sensei"
HOMEPAGE = f"https://github.com/{REPO}"
DESCRIPTION = "Self-hosted AI gateway that compresses prompts before they leave your machine"


def parse_sums(path: Path) -> dict[str, str]:
    """`sha256sum` output -> {filename: digest}.

    The format is `<digest>␣␣<name>`; the second space is a binary-mode marker
    and the name may itself contain spaces, so split exactly twice.
    """
    sums: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, name = line.partition("  ")
        if digest and name:
            sums[name.strip().lstrip("*")] = digest
    return sums


def url_for(version: str, filename: str) -> str:
    return f"{HOMEPAGE}/releases/download/v{version}/{filename}"


def require(sums: dict[str, str], name: str) -> str:
    if name not in sums:
        raise SystemExit(
            f"{name} is not in SHA256SUMS. Either the release job did not build it, "
            f"or it was renamed and this script was not updated.\n"
            f"Present: {', '.join(sorted(sums))}"
        )
    return sums[name]


def homebrew(version: str, sums: dict[str, str]) -> str:
    """A formula with one binary per platform.

    Deliberately not a `depends_on "python"` formula that pip-installs: the
    PyInstaller build has no Python requirement at all, and a Homebrew formula
    that drags in a Python it then has to keep in sync is a support burden for
    a project whose whole pitch is that it stays out of your way.
    """
    mac_arm = "sensei-macos-arm64.tar.gz"
    mac_x86 = "sensei-macos-x86_64.tar.gz"
    linux = "sensei-linux-x86_64.tar.gz"
    return f"""\
# Generated by scripts/render_manifests.py — do not edit by hand.
class Sensei < Formula
  desc "{DESCRIPTION}"
  homepage "{HOMEPAGE}"
  version "{version}"
  license "MIT"

  on_macos do
    on_arm do
      url "{url_for(version, mac_arm)}"
      sha256 "{require(sums, mac_arm)}"
    end
    on_intel do
      url "{url_for(version, mac_x86)}"
      sha256 "{require(sums, mac_x86)}"
    end
  end

  on_linux do
    on_intel do
      url "{url_for(version, linux)}"
      sha256 "{require(sums, linux)}"
    end
  end

  def install
    bin.install "sensei"
  end

  def caveats
    <<~EOS
      Sensei is not code-signed yet. On first run macOS may refuse to open it:
        xattr -d com.apple.quarantine #{{bin}}/sensei

      Get started:
        sensei up            start the server and open the web UI
        sensei setup-tools   point the AI tools on this machine at it
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/sensei --version")
  end
end
"""


def scoop(version: str, sums: dict[str, str]) -> str:
    archive = "sensei-windows-x64.zip"
    return json.dumps(
        {
            "version": version,
            "description": DESCRIPTION,
            "homepage": HOMEPAGE,
            "license": "MIT",
            "architecture": {
                "64bit": {
                    "url": url_for(version, archive),
                    "hash": require(sums, archive),
                }
            },
            "bin": "sensei.exe",
            "checkver": {"github": HOMEPAGE},
            "autoupdate": {
                "architecture": {
                    "64bit": {
                        "url": f"{HOMEPAGE}/releases/download/v$version/sensei-windows-x64.zip"
                    }
                }
            },
        },
        indent=4,
    ) + "\n"


def winget(version: str, sums: dict[str, str]) -> dict[str, str]:
    """winget takes three YAML files in a directory named after the version.

    Hand-written rather than emitted through a YAML library: the backend has no
    YAML dependency, the schema is fixed, and every value here is either a
    literal or a hex digest, so there is nothing to escape.
    """
    installer = "sensei-windows-x64.exe"
    digest = require(sums, installer)
    pkg = "SenseiIssei.Sensei"
    schema = "https://aka.ms/winget-manifest"
    return {
        f"{pkg}.yaml": f"""\
# yaml-language-server: $schema={schema}.version.1.6.0.schema.json
PackageIdentifier: {pkg}
PackageVersion: {version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
""",
        f"{pkg}.installer.yaml": f"""\
# yaml-language-server: $schema={schema}.installer.1.6.0.schema.json
PackageIdentifier: {pkg}
PackageVersion: {version}
InstallerType: portable
Commands:
  - sensei
Installers:
  - Architecture: x64
    InstallerUrl: {url_for(version, installer)}
    InstallerSha256: {digest.upper()}
ManifestType: installer
ManifestVersion: 1.6.0
""",
        f"{pkg}.locale.en-US.yaml": f"""\
# yaml-language-server: $schema={schema}.defaultLocale.1.6.0.schema.json
PackageIdentifier: {pkg}
PackageVersion: {version}
PackageLocale: en-US
Publisher: SenseiIssei
PublisherUrl: https://github.com/SenseiIssei
PackageName: Sensei
PackageUrl: {HOMEPAGE}
License: MIT
LicenseUrl: {HOMEPAGE}/blob/main/LICENSE
ShortDescription: {DESCRIPTION}
Description: >-
  Sensei sits between your AI tools and the model and compresses what they send,
  typically removing most of the tokens in JSON, logs and tool output. It runs
  entirely on your own machine, speaks both the OpenAI and Anthropic wire
  formats, and reports what it saved.
Tags:
  - ai
  - llm
  - developer-tools
  - self-hosted
ManifestType: defaultLocale
ManifestVersion: 1.6.0
""",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="release version without the leading v")
    parser.add_argument("--sums", required=True, type=Path, help="path to SHA256SUMS")
    parser.add_argument("--out", required=True, type=Path, help="directory to write into")
    args = parser.parse_args()

    version = args.version.lstrip("v")
    sums = parse_sums(args.sums)
    if not sums:
        raise SystemExit(f"{args.sums} contained no checksums")

    out = args.out
    (out / "homebrew").mkdir(parents=True, exist_ok=True)
    (out / "scoop").mkdir(parents=True, exist_ok=True)
    winget_dir = out / "winget" / "manifests" / "s" / "SenseiIssei" / "Sensei" / version
    winget_dir.mkdir(parents=True, exist_ok=True)

    (out / "homebrew" / "sensei.rb").write_text(homebrew(version, sums), encoding="utf-8")
    (out / "scoop" / "sensei.json").write_text(scoop(version, sums), encoding="utf-8")
    for name, body in winget(version, sums).items():
        (winget_dir / name).write_text(body, encoding="utf-8")

    print(f"Rendered manifests for v{version} into {out}", file=sys.stderr)
    for path in sorted(out.rglob("*")):
        if path.is_file():
            print(f"  {path.relative_to(out)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
