# PyInstaller spec for sensei.exe — a single-file launcher that serves the
# Sensei backend + bundled web UI. Build with:
#
#     pip install pyinstaller
#     (cd frontend && npm install && npm run build)   # so the UI is bundled
#     pyinstaller packaging/sensei.spec --noconfirm
#
# Output: dist/sensei.exe
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_submodules

# SPECPATH is the directory holding this file, i.e. <repo>/packaging. So the
# repository root is exactly one level up.
#
# This read `.parents[0]` and then `.parent` again, which lands one level above
# the checkout — `ERROR: script '/home/runner/work/Sensei/packaging/launcher.py'
# not found`, missing the second `Sensei/`. Every installer job had been failing
# on it, which nobody saw because the release workflow had never been run: there
# were no tags in the repository at all until v0.1.0.
here = Path(SPECPATH).resolve()
repo = here.parent

# Bundle the built web UI if it exists.
datas = []
dist = repo / "frontend" / "dist"
if dist.exists():
    datas.append((str(dist), "frontend/dist"))

# `mcp` is imported lazily inside build_server(), so PyInstaller's static
# analysis never sees it — the binary built fine and then `sensei mcp` died with
# ModuleNotFoundError. It has to be collected explicitly. Optional at build
# time: a contributor without the extra installed still gets a working binary,
# minus the MCP server.
try:
    _mcp = collect_submodules("mcp")
except Exception:  # pragma: no cover - the extra simply isn't installed
    _mcp = []

# The Rust accelerator, when the build environment has it. Imported inside a
# `try` in three compressor modules, so PyInstaller's static analysis never sees
# it and the binary shipped without it for every release — `sensei doctor` said
# "Rust accelerator: not installed" on an installed copy, and every compression
# took the pure-Python path at roughly a fifth of the speed.
#
# Optional at build time on purpose: a contributor without a Rust toolchain
# still gets a working binary, just a slower one.
try:
    _accel = collect_submodules("sensei_core")
except Exception:  # pragma: no cover — the wheel simply isn't installed
    _accel = []

hiddenimports = (
    collect_submodules("sensei")
    + collect_submodules("uvicorn")
    + _mcp
    + _accel
    + ["fastapi", "pydantic", "pydantic_settings", "httpx", "tiktoken", "anyio", "starlette"]
)

a = Analysis(
    [str(repo / "packaging" / "launcher.py")],
    pathex=[str(repo / "backend")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["torch", "transformers", "vllm", "llama_cpp", "PySide6"],
    noarchive=False,
)
pyz = PYZ(a.pure)

# Generated by packaging/make_icon.py, so the tray icon, the executable and the
# installer all render the same drawing. Absent on a checkout that has not run
# it — PyInstaller is fine with icon=None.
_icon = here / "sensei.ico"

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="sensei",
    console=True,
    disable_windowed_traceback=False,
    upx=True,
    icon=str(_icon) if _icon.exists() else None,
)

# A second binary from the same code, built without a console.
#
# One executable cannot do both jobs. A console build always allocates a window
# when launched from a shortcut — so "runs quietly in the tray" flashes, or
# leaves, a black rectangle on the desktop. A windowed build has nowhere to
# print, so `sensei doctor` would produce nothing at all.
#
# Windows has solved this the same way since forever — `python.exe` and
# `pythonw.exe` — and copying that costs one extra EXE() from an Analysis that
# has already been done. `senseiw` defaults to the tray rather than to `up`,
# because a server with no console and no icon is a process you can only stop
# in Task Manager.
exew = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="senseiw",
    console=False,
    disable_windowed_traceback=False,
    upx=True,
    icon=str(_icon) if _icon.exists() else None,
)
